---
- hosts: localhost
  connection: local
  become: true

  tasks:
# It is not trivial to install stuff on mac with homebrew
# TODO figure out later, here are some references:
# https://github.com/geerlingguy/mac-dev-playbook
# https://github.com/geerlingguy/ansible-collection-mac
#    - name: install essentials
#      community.general.homebrew:
#        update_homebrew: true
#        name: htop
#        state: present
#    - name: install essentials
#      package:
#        name:
#          - htop
#          - zsh

    - name: zsh dirs
      copy:
        src: files/zsh_custom/
        dest: /Users/alagodich/.oh-my-zsh/custom/
        owner: alagodich
        group: staff
        mode: 0644

    - name: zsh config
      copy:
        src: files/.zshrc
        dest: /Users/alagodich/.zshrc
        owner: alagodich
        group: staff
        mode: 0644

    - name: vimrc
      copy:
        src: files/.vimrc
        dest: /Users/alagodich/.vimrc
        owner: alagodich
        group: staff
        mode: 0644

    - name: vim config
      copy:
        src: files/vim/
        dest: /Users/alagodich/.vim/
        owner: alagodich
        group: staff
        mode: 0644

    - name: enable press and hold
      shell: defaults write -g ApplePressAndHoldEnabled -bool false

