---
- hosts: localhost
  connection: local

  tasks:
    - name: myzsh config
      copy:
        src: files/my.zsh
        dest: /Users/alagodich/.oh-my-zsh/custom/my.test
        owner: alagodich
        group: staff
        mode: 0644