---
- hosts: localhost
  connection: local

  tasks:
    - name: install essentials
      become: false
      community.general.homebrew:
        update_homebrew: true
        name: htop
        state: present

    - name: zsh config
      copy:
        src: files/.zshrc
        dest: /Users/alagodich/test.zshrc
        owner: alagodich
        group: staff
        mode: 0644

    - name: myzsh config
      copy:
        src: files/my.zsh
        dest: /Users/alagodich/.oh-my-zsh/custom/my.zsh
        owner: alagodich
        group: staff
        mode: 0644