---
- hosts: localhost
  connection: local
  become: true

  tasks:
# It is not trivial to install stuff on mac with homebrew
# TODO figure out later, here are some references:
# https://github.com/geerlingguy/mac-dev-playbook
# https://github.com/geerlingguy/ansible-collection-mac
#    - name: install essentials
#      community.general.homebrew:
#        update_homebrew: true
#        name: htop
#        state: present
#    - name: install essentials
#      package:
#        name:
#          - htop
#          - zsh

    - name: zsh config
      copy:
        src: files/.zshrc
        dest: /Users/alagodich/test.zshrc
        owner: alagodich
        group: staff
        mode: 0644

    - name: myzsh config
      copy:
        src: files/my.zsh
        dest: /Users/alagodich/.oh-my-zsh/custom/my.zsh
        owner: alagodich
        group: staff
        mode: 0644